### ISSUE TITLE
ui width not correct

### ISSUE THREAD

**Issue by bhuism** [turing-machines/BMC-Firmware#229]
using build https://github.com/turing-machines/BMC-Firmware/actions/runs/12650710433

the screen is (at certain windows widths) as below:

![image](https://github.com/user-attachments/assets/a9dbf76f-1478-4192-83b8-495d2f5b6ae0)

just resize your window horizontally to reproduce

**Comment by gjrtimmer** [comment]
@bhuism Could you check if this was already reported or fixed in the [BMC-UI Repository](https://github.com/turing-machines/BMC-UI/issues) and if not report it there.

**Comment by bhuism** [comment]
I just tested with release v2.1.0 tpu of BMC-firmware (which has BMC-UI v3.3.3) and it was not fixed.
BMC-UI repo latest release is version 3.3.6, I don't know if 3.3.6 version still has it.

it was not reported in https://github.com/turing-machines/BMC-UI.
